version: "3.8"

services:
  project-api:
    image: project-api
    build:
      dockerfile: Dockerfile
    ports:
      - "5001:80" # Map HTTP port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-project;Database=project-db;User Id=postgres;Password=postgres
    depends_on:
      db-project:
        condition: service_healthy

  db-project:
    image: postgres
    environment:
      POSTGRES_DB: project-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
